version: '3.7'

services:
  postgres:
    image: postgres:16
    container_name: quarkus-postgres16
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: quarkus-keycloak
    command: ["start"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: DEBUG
      ROOT_LOGLEVEL: DEBUG
      KC_PROXY: edge
      KC_HOSTNAME: sso.dylanops.com
      KC_HOSTNAME_STRICT: false
#      KC_DB: postgres
#      KC_DB_URL: jdbc:postgresql://postgres/keycloak
#      KC_DB_SCHEMA: keycloak
#      KC_DB_USERNAME: ${POSTGRES_USER}
#      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - postgres

volumes:
  postgres-data:

networks:
  app:
    driver: bridge