version: '3.7'

services:
  mysql:
    image: mysql:8.0.35-oracle
    container_name: quarkus-mysql8
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - app
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: quarkus-keycloak
    command: ["start"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: edge
      KC_HOSTNAME: sso.dylanops.com
      KC_HOSTNAME_STRICT: false
#      KC_DB: mysql
#      KC_DB_SCHEMA: keycloak
#      KC_DB_URL_HOST: mysql
#      KC_DB_URL: jdbc:mysql://mysql/keycloak
#      KC_DB_USERNAME: ${MYSQL_USER}
#      KC_DB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - mysql

volumes:
  mysql-data:

networks:
  app:
    driver: bridge